// Auto-generated by scripts/wgsl_scanner.js
// Do not manually edit this file!

export interface FragmentInput {
    uv: any;
}

export const FragmentInputLayout = {
    SIZE: 8,
    ALIGN: 8,
    OFFSET: {
        uv: 0, // size: 8
    }
};

export interface VertexOutput {
    position: any;
    uv: any;
}

export const VertexOutputLayout = {
    SIZE: 32,
    ALIGN: 16,
    OFFSET: {
        position: 0, // size: 16
        uv: 16, // size: 8
    }
};

export interface BoxUniforms {
    minPos: any;
    maxPos: any;
    color: any;
}

export const BoxUniformsLayout = {
    SIZE: 48,
    ALIGN: 16,
    OFFSET: {
        minPos: 0, // size: 16
        maxPos: 16, // size: 16
        color: 32, // size: 16
    }
};

export interface GBufferOutput {
    albedo: any;
    normal: any;
    position: any;
    specular_material: any;
}

export const GBufferOutputLayout = {
    SIZE: 64,
    ALIGN: 16,
    OFFSET: {
        albedo: 0, // size: 16
        normal: 16, // size: 16
        position: 32, // size: 16
        specular_material: 48, // size: 16
    }
};

export interface IBLResult {
    kD: any;
    iblIrradiance: any;
    specularIBL: any;
}

export const IBLResultLayout = {
    SIZE: 48,
    ALIGN: 16,
    OFFSET: {
        kD: 0, // size: 12
        iblIrradiance: 16, // size: 12
        specularIBL: 32, // size: 12
    }
};

export interface Ray {
    origin: any;
    direction: any;
}

export const RayLayout = {
    SIZE: 32,
    ALIGN: 16,
    OFFSET: {
        origin: 0, // size: 12
        direction: 16, // size: 12
    }
};

export interface BVHBoundingBox {
    min: any;
    max: any;
}

export const BVHBoundingBoxLayout = {
    SIZE: 24,
    ALIGN: 4,
    OFFSET: {
        min: 0, // size: 12
        max: 12, // size: 12
    }
};

export interface BVHNode {
    bounds: any;
    rightChildOrTriangleOffset: number;
    splitAxisOrTriangleCount: number;
}

export const BVHNodeLayout = {
    SIZE: 32,
    ALIGN: 4,
    OFFSET: {
        bounds: 0, // size: 24
        rightChildOrTriangleOffset: 24, // size: 4
        splitAxisOrTriangleCount: 28, // size: 4
    }
};

export interface IntersectionResult {
    didHit: any;
    indices: any;
    normal: any;
    barycoord: any;
    side: number;
    dist: number;
}

export const IntersectionResultLayout = {
    SIZE: 64,
    ALIGN: 16,
    OFFSET: {
        didHit: 0, // size: 0
        indices: 0, // size: 16
        normal: 16, // size: 12
        barycoord: 32, // size: 12
        side: 44, // size: 4
        dist: 48, // size: 4
    }
};

export interface Surfel {
    position: any;
    radius: number;
    normal: any;
    age: number;
    irradiance: any;
    variance: number;
    shortMean: any;
    pGuide: number;
}

export const SurfelLayout = {
    SIZE: 64,
    ALIGN: 16,
    OFFSET: {
        position: 0, // size: 12
        radius: 12, // size: 4
        normal: 16, // size: 12
        age: 28, // size: 4
        irradiance: 32, // size: 12
        variance: 44, // size: 4
        shortMean: 48, // size: 12
        pGuide: 60, // size: 4
    }
};

export interface SurfelGridConstants {
    gridMin: any;
    pad0: number;
    gridMax: any;
    pad1: number;
    cellsX: number;
    cellsY: number;
    cellsZ: number;
    maxSurfelsPerCell: number;
    maxSurfels: number;
    allocatedCount: number;
    raysPerSurfel: number;
    pad2: number;
}

export const SurfelGridConstantsLayout = {
    SIZE: 64,
    ALIGN: 16,
    OFFSET: {
        gridMin: 0, // size: 12
        pad0: 12, // size: 4
        gridMax: 16, // size: 12
        pad1: 28, // size: 4
        cellsX: 32, // size: 4
        cellsY: 36, // size: 4
        cellsZ: 40, // size: 4
        maxSurfelsPerCell: 44, // size: 4
        maxSurfels: 48, // size: 4
        allocatedCount: 52, // size: 4
        raysPerSurfel: 56, // size: 4
        pad2: 60, // size: 4
    }
};

export interface SurfelGuidanceTile {
    luminanceBits: any;
}

export const SurfelGuidanceTileLayout = {
    SIZE: 256,
    ALIGN: 16,
    OFFSET: {
        luminanceBits: 0, // size: 256
    }
};

export interface SurfelDepthTile {
    moments: any;
}

export const SurfelDepthTileLayout = {
    SIZE: 256,
    ALIGN: 16,
    OFFSET: {
        moments: 0, // size: 256
    }
};

export interface Counter {
    count: any;
}

export const CounterLayout = {
    SIZE: 4,
    ALIGN: 4,
    OFFSET: {
        count: 0, // size: 4
    }
};

export interface Allocator {
    count: any;
}

export const AllocatorLayout = {
    SIZE: 4,
    ALIGN: 4,
    OFFSET: {
        count: 0, // size: 4
    }
};

export interface GenParams {
    face_size: number;
    sun_dir_x: number;
    sun_dir_y: number;
    sun_dir_z: number;
}

export const GenParamsLayout = {
    SIZE: 16,
    ALIGN: 4,
    OFFSET: {
        face_size: 0, // size: 4
        sun_dir_x: 4, // size: 4
        sun_dir_y: 8, // size: 4
        sun_dir_z: 12, // size: 4
    }
};

export interface PrefilterParams {
    roughness: number;
    face_size: number;
    num_samples: number;
    _pad: number;
}

export const PrefilterParamsLayout = {
    SIZE: 16,
    ALIGN: 4,
    OFFSET: {
        roughness: 0, // size: 4
        face_size: 4, // size: 4
        num_samples: 8, // size: 4
        _pad: 12, // size: 4
    }
};

export interface VertexInput {
    pos: any;
    nor: any;
    uv: any;
    tangent: any;
}

export const VertexInputLayout = {
    SIZE: 64,
    ALIGN: 16,
    OFFSET: {
        pos: 0, // size: 12
        nor: 16, // size: 12
        uv: 32, // size: 8
        tangent: 48, // size: 16
    }
};

export interface AllocationState {
    counter: any;
    total_requested: any;
}

export const AllocationStateLayout = {
    SIZE: 8,
    ALIGN: 4,
    OFFSET: {
        counter: 0, // size: 4
        total_requested: 4, // size: 4
    }
};

