import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { WgslReflect } from 'wgsl_reflect';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const shadersDir = path.resolve(__dirname, '../src/shaders');
const outputFile = path.resolve(__dirname, '../src/shaders/WGSLTypes.ts');

function findWgslFiles(dir, fileList = []) {
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const filePath = path.join(dir, file);
        if (fs.statSync(filePath).isDirectory()) {
            findWgslFiles(filePath, fileList);
        } else if (filePath.endsWith('.wgsl')) {
            fileList.push(filePath);
        }
    }
    return fileList;
}

const wgslFiles = findWgslFiles(shadersDir);

let outputTS = `// Auto-generated by scripts/wgsl_scanner.js
// Do not manually edit this file!

`;

const generatedStructs = new Set();
const allStructs = {};

wgslFiles.forEach(file => {
    const code = fs.readFileSync(file, 'utf-8');
    try {
        const reflect = new WgslReflect(code);
        reflect.structs.forEach(struct => {
            if (!allStructs[struct.name]) {
                allStructs[struct.name] = struct;
            }
        });
    } catch (e) {
        console.warn(`[WgslReflect] Could not parse ${file}: ${e.message}`);
    }
});

function getTSType(wgslType) {
    if (!wgslType) return 'any';
    const t = typeof wgslType === 'string' ? wgslType : wgslType.name;
    if (t === 'f32' || t === 'i32' || t === 'u32') return 'number';
    if (t === 'vec2' || t === 'vec3' || t === 'vec4') return 'Float32Array | number[]';
    if (t === 'mat4x4') return 'Float32Array | number[]';
    return 'any';
}

for (const [name, struct] of Object.entries(allStructs)) {
    outputTS += `export interface ${name} {
`;
    struct.members.forEach(m => {
        outputTS += `    ${m.name}: ${getTSType(m.type)};\n`;
    });
    outputTS += `}

export const ${name}Layout = {
    SIZE: ${struct.size},
    ALIGN: ${struct.align},
    OFFSET: {
`;
    struct.members.forEach(m => {
        outputTS += `        ${m.name}: ${m.offset}, // size: ${m.size}\n`;
    });
    outputTS += `    }
};

`;
}

fs.writeFileSync(outputFile, outputTS);
console.log(`[WGSL Scanner] Generated types for ${Object.keys(allStructs).length} structs into WGSLTypes.ts`);
